### PR TITLE
Fix ssize_t typedef on Windows

### PR DESCRIPTION
**Pull request by seanyen**
`ssize_t` should be a signed integer type. `AsyncReadBuffer::read()` uses the signed data type to decide its code path.

### CODE REVIEW

**Comment by kejxu** [comment]
looks good, question:

why are we using `_MSC_VER` instead of `_WIN32` here?

**Comment by seanyen** [comment]
@kejxu `_MSC_VER` is a macro defined uniquely by Microsoft Visual C\C++ compiler, but `_WIN32` is a more common macro defined even on `gcc`, `clang`. I was thinking that `ssize_t` is more tight with what toolchain developer uses, but on a second check, `ssize_t` is a thing defined in `POSIX` spec but not in `C99`. Maybe neither of them is good enough to check. :/

**Comment by kejxu** [comment]
> defined in `POSIX` spec but not in `C99`

just curious, isn't `POSIX` the opposite to `win32` (in most cases, given we're not working with MacOS anyways)?

I am wondering if `_MSC_VER` only means the code is compiled with MSVC, regardless of the platform; yet `_WIN32` is guaranteed to be compiled on win32 platform.

**Comment by seanyen** [comment]
> just curious, isn't `POSIX` the opposite to `win32` (in most cases, given we're not working with MacOS anyways)?

No, it not really mutual exclusive. `POSIX` is just yet another abstract API layer and theoretically it can happen on every system. However I cannot argue in most cases, `*nix` system provides much better support for it.

Taking a step back on the `ssize_t` usage, I see another approach is to modernize the code to use `int64_t` C++11 data type which should be more generic across platforms.

**Comment by kejxu** [comment]
> Taking a step back on the `ssize_t` usage, I see another approach is to modernize the code to use `int64_t` C++11 data type which should be more generic across platforms.

Thanks for the explanation!

**Pull request merged**
